using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using DG.Tweening;

public class Kulakl覺k : MonoBehaviour
{
    //[SerializeField] GameObject Kulaklik;
    [SerializeField] float AnimYmove;
    [SerializeField] float Animdu;

    // Start is called before the first frame update
    void Start()
    {
        //Kulaklik = gameObject.GetComponent<GameObject>();
        DOTween.Init();
        transform.DOLocalMoveY(AnimYmove, Animdu).SetLoops(-1, LoopType.Yoyo);

    }

    // Update is called once per frame
    void Update()
    {

    }
    private void OnTriggerEnter(Collider other)
    {
        if (other.tag == "Player")
        {
            PlayerController.numberofKulakl覺k += 1;
            Debug.Log("Kulakl覺k:" + PlayerController.numberofKulakl覺k);
            Destroy(gameObject);
        }
        
    }
   
}

